#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

case ARGV[1]
when 'list-state-machines'
  puts '{"sdkResponseMetadata":null,"sdkHttpMetadata":null,"stateMachines":[],"nextToken":null}'
end
